# Multiple linear regression and adjusted R-squared.ipynb

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')

from sklearn.linear_model import LinearRegression

## Load the data

In [2]:
data = pd.read_csv('1.02. Multiple linear regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [3]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## Create multiple linear regression

### Declare dependent and independent variables

In [4]:
x= data[['SAT','Rand 1,2,3']]
y= data['GPA']

### Regression itself

In [5]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression()

In [6]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [7]:
reg.intercept_

0.29603261264909486

### Calculating R-squared

- The R-squared is a universal measure to evaluate how well linear regressions fare and compare   
- reg.score(x,y) -> returns the R-squared of a linear regression

In [8]:
reg.score(x,y)

0.4066811952814283

### Adjusted R-squared

- remember that : The adjusted R-squared is a much more appropriate measure for a multiple linear regression   
- The adjusted R-squared steps on the R-squared and adjusts for the number of variable included in the model   
- If we are using features with little or no explanatory power, the R-squared would increase, nonetheles. Thus, we need to penalize the successive usage through the adjusted R-squared

### **Formula for Adjusted $R^2$**
$R^2_{adj.} = 1 -(1 -R^2)*\frac{n-1}{n-p-1}$

- n =84 (the number of observations)  
- p =2 (the number of predictors )

In [9]:
x.shape

(84, 2)

In [10]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

# Feature selection

- How to detect variables whisch are unneeded in a model?   
- Feature selection is a very important procedure and machine learning as it simplifies models, which make them much easier to interpret by data scientist. Through this process.  
- Feature selection -> simplifies models, improves speed and prevents a series of unwanted issues arising from having too many features      
- in statsmodel we were saying that if a variable has a p-value > 0.05 we can disregard it   
- **f_refression** -> creates simple linear regressions of each feature and dependent variable
- **The p-value of F-stat = the p-value of the only independent variable**

In [11]:
from sklearn.feature_selection import f_regression

In [12]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [13]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [14]:
p_values.round(3)

array([0.   , 0.676])

# Creating a summary table

In [15]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [16]:
reg_summary ['Coefficients'] = reg.coef_
reg_summary ['p-values'] = p_values.round(3)

In [18]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

- P-values are one of the best ways to determine if a variable is redundant,
but they provide no information whasoever about HOW USEFUL a variable is